FROM nginx:1.16.1-alpine
WORKDIR /var/lib/service
COPY . .

COPY dockerbuild/nginx.conf /etc/nginx/nginx.conf
# 配置https需要证书
COPY dockerbuild/server.crt /etc/ssl/certs/
COPY dockerbuild/server.key /etc/ssl/certs/
