# Use a Debian-based image as the base image
FROM debian:latest

# Install build essentials and Git to compile Redis from source
RUN apt-get update && apt-get install -y build-essential git

# Clone Redis source code from GitHub
RUN git clone https://github.com/redis/redis.git /redis

# Set the working directory to /redis
WORKDIR /redis

# Compile Redis
RUN make

# 安装redis-server和redis-cli
RUN make install

# Copy Redis cluster config file
COPY ./redis.conf /redis/redis.conf

# 默认命令启动Redis server
CMD ["src/redis-server", "/redis/redis.conf"]
